name: verify-version-change
description: Verify change package version

inputs:
  path:
    description: Package path
    required: false
    default: .

runs:
  using: node16
  main: dist/index.js

outputs:
  changed:
    description: true if version was bumped
  version:
    description: new version
