name: Get LGTM alerts

inputs:
  repository:
    description: GitHub repository { github.repository }
    required: true

outputs:
  changed:
    description: 'true' if changes detected
    value: ${{ steps.detection.outputs.changed }}

runs:
  using: composite
  steps:
    - name: Get Project info
        run: |
          RESPONSE=$(curl -X GET "https://lgtm.com/api/v1.0/projects/g/${{ inputs.repository }}" -H 'Content-Type: application/json')
          echo "PROJECT=$RESPONSE" >> $GITHUB_ENV
      - name: Get Latest Analysis info
        run: |
          RESPONSE=$(curl -X GET 'https://lgtm.com/api/v1.0/analyses/${{ fromJSON(env.PROJECT).id }}/commits/latest' -H 'Accept: application/json')
          echo "ANALYSIS=$RESPONSE" >> $GITHUB_ENV
      - name: Get SARIF
        run: |
          curl -X GET "https://lgtm.com/api/v1.0/analyses/${{ fromJSON(env.ANALYSIS).id }}/alerts" -H 'Accept: application/sarif+json' >> lgtm.sarif
